### ISSUE TITLE
Cannot run replace_in_table.py

### ISSUE THREAD

**Issue by mklippey** [springinnovate/pestcontrol_livingdatabase#2]
I am trying to use replace_in_table.py. When I use "--help", it looks like it calls for the path to the base table, the path to the replacement table, and then specifying the field_name to replace and a target_suffix. 

My code looks like this:
python replace_in_table.py C:\Users\mklip\pestcontrol_livingdatabase\plotdata.vineyards.csv C:\Users\mklip\pestcontrol_livingdatabase\candidate_table_5_3.0.csv --field_name technician --target_suffix replaced

I get this error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 198: character maps to <undefined>

Where am I going wrong? I tried adding a comma between paths as well, but that put out a new error: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mklip\\pestcontrol_livingdatabase\\plotdata.vineyards.csv,'

You mentioned that it might be because the data aren't in a CSV format, but I checked and they definitely are. 

Thanks!

**Comment by richpsharp** [comment]
Attaching relevant CSV tables here for debugging.

[candidate_table_5_3.0.csv](https://github.com/springinnovate/pestcontrol_livingdatabase/files/11761879/candidate_table_5_3.0.csv)
[plotdata.vineyards.csv](https://github.com/springinnovate/pestcontrol_livingdatabase/files/11761881/plotdata.vineyards.csv)

**Comment by richpsharp** [comment]
Hi @mklippey, short answer is I've "fixed" this but it's worth understanding what's happening in the replace table and why it's happening so we can make good decisions about what strings to use to replace any dirty data.

Issue is that the "vineyard" table has a "0x90" character in it. Specifically in this name "RAQUEL HERRADOR MARTNEZ" (note even github doesn't know what to do with that character and makes an empty box). In general 0x90 doesn't mean anything, you have to know what the "encoding scheme" is. For example if the encoding scheme is "utf-8" then 0x41 would represent "A". On the back end we can't tell just from the file what the encoding scheme is, which is frustrating -- like there's no way the file can tell us what any of the characters are supposed to be, so instead we make educated guesses. The tricky thing is that 0x90 character isn't a printable character in ANY modern encoding scheme.

So offhand, I wonder how that even happened, like did those data get mixed up with other data or copied and pasted and translated? -- I don't know. The point on my end is there's no way to programmatically even GUESS what 0x90 is supposed to be, so the only thing I can do without crashing is to mark it as "unknown" just like slack does above.

So here's how you'll encounter this in practice. In the base vinyards data we encounter this name with an erroneous character like this screenshot:

![image](https://github.com/springinnovate/pestcontrol_livingdatabase/assets/7773490/972a4ee3-5242-4d36-9fbd-1163ec69a49b)

(note excel is inconsistently displaying this odd character where in the sheet you don't see anything and in the cell editor showing it as a whitespace). Next, when you run `clean_table.py` you'll end up with a translation table like this screenshot:

![image](https://github.com/springinnovate/pestcontrol_livingdatabase/assets/7773490/d835633d-132d-4a34-a3dc-8b962a0fc4b7)

So this is the time to catch that weird character and fill in anything you like for it that's readable. But if for some reason you don't, you'll end up with the third screenshot:
 
![image](https://github.com/springinnovate/pestcontrol_livingdatabase/assets/7773490/7e8b06db-e512-4b41-8b80-f6c8ec8b2534)

Now it's been consistently replaced with the universal "I don't know what this character is"-character. If you see this you'll know that you should go back to the replace table and fix that character and run it again.

**Comment by richpsharp** [comment]
@mklippey I think this is closed, let me know if not!
